In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# **Working with DataFrames in pandas:**

>**What is DataFrame?**

**DataFrame. DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object.**

## 65: what is A DataFrame

# 67: Creating DataFrames

In [2]:
names =["olga","Andrew","Brian","Telulah","Nicole","Tilda"]

In [3]:
ages =[29,21,45,23,39,46]

In [4]:
married=["False","True","True","True","False","True"]

In [5]:
pd.DataFrame({"name":names,"age":ages,"married":married})

      name  age married
0     olga   29   False
1   Andrew   21    True
2    Brian   45    True
3  Telulah   23    True
4   Nicole   39   False
5    Tilda   46    True

In [6]:
# NOTE: when you creating dataFrame length of the all the attributes or columns must be the same otherwise it give error.

# 68: 4 more way to creat DataFrame
> download the orginal file and practice more later on.

# **69: The info() method.**

In [7]:
df = pd.DataFrame({"name":names,"age":ages,"married":married})

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     6 non-null      object
 1   age      6 non-null      int64
 2   married  6 non-null      object
dtypes: int64(1), object(2)
memory usage: 272.0+ bytes

In [9]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     6 non-null      object
 1   age      6 non-null      int64
 2   married  6 non-null      object
dtypes: int64(1), object(2)
memory usage: 272.0+ bytes

In [10]:
df.info(max_cols=4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     6 non-null      object
 1   age      6 non-null      int64
 2   married  6 non-null      object
dtypes: int64(1), object(2)
memory usage: 272.0+ bytes

In [11]:
df.info(verbose =False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Columns: 3 entries, name to married
dtypes: int64(1), object(2)
memory usage: 272.0+ bytes

In [12]:
df.info(memory_usage=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     6 non-null      object
 1   age      6 non-null      int64
 2   married  6 non-null      object
dtypes: int64(1), object(2)
memory usage: 272.0+ bytes

In [13]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     6 non-null      object
 1   age      6 non-null      int64
 2   married  6 non-null      object
dtypes: int64(1), object(2)
memory usage: 919.0 bytes

# **70: Reading in Nutrition Data**

In [14]:
dataurl = "https://andybek.com/pandas-nutrition" # data is availbel in kaggel as well.

In [15]:
nutrition = pd.read_csv(dataurl)

In [16]:
nutrition.head()

   Unnamed: 0             name serving_size  ...  caffeine theobromine    water
0           0       Cornstarch        100 g  ...   0.00 mg     0.00 mg   8.32 g
1           1     Nuts, pecans        100 g  ...   0.00 mg     0.00 mg   3.52 g
2           2    Eggplant, raw        100 g  ...   0.00 mg     0.00 mg  92.30 g
3           3   Teff, uncooked        100 g  ...         0           0   8.82 g
4           4  Sherbet, orange        100 g  ...   0.00 mg     0.00 mg  66.10 g

[5 rows x 77 columns]

In [17]:
nutrition.info(memory_usage="deep",verbose= False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8789 entries, 0 to 8788
Columns: 77 entries, Unnamed: 0 to water
dtypes: int64(3), object(74)
memory usage: 39.2 MB

# 71:Some Cleanup:Removing The Duplicated Index

In [18]:
nutrition.head()

   Unnamed: 0             name serving_size  ...  caffeine theobromine    water
0           0       Cornstarch        100 g  ...   0.00 mg     0.00 mg   8.32 g
1           1     Nuts, pecans        100 g  ...   0.00 mg     0.00 mg   3.52 g
2           2    Eggplant, raw        100 g  ...   0.00 mg     0.00 mg  92.30 g
3           3   Teff, uncooked        100 g  ...         0           0   8.82 g
4           4  Sherbet, orange        100 g  ...   0.00 mg     0.00 mg  66.10 g

[5 rows x 77 columns]

In [19]:
nutrition.drop("Unnamed: 0",axis = 1,inplace = True) # axis and inplace is important parameters

In [20]:
nutrition.head(2)

           name serving_size  calories  ... caffeine theobromine   water
0    Cornstarch        100 g       381  ...  0.00 mg     0.00 mg  8.32 g
1  Nuts, pecans        100 g       691  ...  0.00 mg     0.00 mg  3.52 g

[2 rows x 76 columns]

In [21]:
# 2way to do: we can use unnamed column as index column. 
# nutrition.set_index("Unamed: 0")

In [22]:
# 3RD way is :
dataurl

'https://andybek.com/pandas-nutrition'

In [23]:
nutrition= pd.read_csv(dataurl, index_col=[0])

In [24]:
nutrition.head()

              name serving_size  calories  ... caffeine theobromine    water
0       Cornstarch        100 g       381  ...  0.00 mg     0.00 mg   8.32 g
1     Nuts, pecans        100 g       691  ...  0.00 mg     0.00 mg   3.52 g
2    Eggplant, raw        100 g        25  ...  0.00 mg     0.00 mg  92.30 g
3   Teff, uncooked        100 g       367  ...        0           0   8.82 g
4  Sherbet, orange        100 g       144  ...  0.00 mg     0.00 mg  66.10 g

[5 rows x 76 columns]

# 72:The Sample() Method

In [25]:
 #nutrition.sample()

In [26]:
#nutrition.sample(random_state= 12)

In [27]:
#nutrition.sample(n= 3)
#nutrition.sample(frac=0.01)

# 73: Sampling with Replacement or weights

In [28]:
# With or with out Replacement
#nutrition.sample(n =3, replace = True)

In [29]:
# Weighted sampling 
weights = pd.Series([10,10,10,1,2],index=[7,17,29,5,6])

In [30]:
weights

7     10
17    10
29    10
5      1
6      2
dtype: int64

In [31]:
nutrition.sample(n =3, weights = weights)

                      name serving_size  calories  ... caffeine theobromine    water
29  Nuts, dried, pine nuts        100 g       673  ...  0.00 mg     0.00 mg   2.28 g
6         Taro leaves, raw        100 g        42  ...  0.00 mg     0.00 mg  85.66 g
17  Peppers, raw, jalapeno        100 g        29  ...  0.00 mg     0.00 mg  91.69 g

[3 rows x 76 columns]

# **74: How Are Random Numbers Generated?**
This top is moslty computer and phisics science.

it is just good to know we do not need to go more details

in pandas.

## **75: DataFrame Axes:**

In [32]:
#nutrition.axes

In [33]:
nutrition.axes[0] # this shows us all the index numbers in our dataFrame or row numbers.

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            8779, 8780, 8781, 8782, 8783, 8784, 8785, 8786, 8787, 8788],
           dtype='int64', length=8789)

In [34]:
#nutrition.axes[0][20] # this show's us index number 20 or row nuber 20 it is simillar to this code.  
nutrition.index[20]

20

In [35]:
nutrition.axes[1] # retunr list of our columns.

Index(['name', 'serving_size', 'calories', 'total_fat', 'saturated_fat',
       'cholesterol', 'sodium', 'choline', 'folate', 'folic_acid', 'niacin',
       'pantothenic_acid', 'riboflavin', 'thiamin', 'vitamin_a',
       'vitamin_a_rae', 'carotene_alpha', 'carotene_beta',
       'cryptoxanthin_beta', 'lutein_zeaxanthin', 'lucopene', 'vitamin_b12',
       'vitamin_b6', 'vitamin_c', 'vitamin_d', 'vitamin_e', 'tocopherol_alpha',
       'vitamin_k', 'calcium', 'copper', 'irom', 'magnesium', 'manganese',
       'phosphorous', 'potassium', 'selenium', 'zink', 'protein', 'alanine',
       'arginine', 'aspartic_acid', 'cystine', 'glutamic_acid', 'glycine',
       'histidine', 'hydroxyproline', 'isoleucine', 'leucine', 'lysine',
       'methionine', 'phenylalanine', 'proline', 'serine', 'threonine',
       'tryptophan', 'tyrosine', 'valine', 'carbohydrate', 'fiber', 'sugars',
       'fructose', 'galactose', 'glucose', 'lactose', 'maltose', 'sucrose',
       'fat', 'saturated_fatty_acids', 'monounsaturated_fatty_acids',
       'polyunsaturated_fatty_acids', 'fatty_acids_total_trans', 'alcohol',
       'ash', 'caffeine', 'theobromine', 'water'],
      dtype='object')

In [36]:
nutrition.axes[1][69]

'polyunsaturated_fatty_acids'

In [37]:
nutrition.columns[69]

'polyunsaturated_fatty_acids'

In [38]:
# The axes parameter
#nutrition.dropna(axis = 0)

In [39]:
# 0 => rows : and 1=> columns

In [40]:
nutrition.axes[1]

Index(['name', 'serving_size', 'calories', 'total_fat', 'saturated_fat',
       'cholesterol', 'sodium', 'choline', 'folate', 'folic_acid', 'niacin',
       'pantothenic_acid', 'riboflavin', 'thiamin', 'vitamin_a',
       'vitamin_a_rae', 'carotene_alpha', 'carotene_beta',
       'cryptoxanthin_beta', 'lutein_zeaxanthin', 'lucopene', 'vitamin_b12',
       'vitamin_b6', 'vitamin_c', 'vitamin_d', 'vitamin_e', 'tocopherol_alpha',
       'vitamin_k', 'calcium', 'copper', 'irom', 'magnesium', 'manganese',
       'phosphorous', 'potassium', 'selenium', 'zink', 'protein', 'alanine',
       'arginine', 'aspartic_acid', 'cystine', 'glutamic_acid', 'glycine',
       'histidine', 'hydroxyproline', 'isoleucine', 'leucine', 'lysine',
       'methionine', 'phenylalanine', 'proline', 'serine', 'threonine',
       'tryptophan', 'tyrosine', 'valine', 'carbohydrate', 'fiber', 'sugars',
       'fructose', 'galactose', 'glucose', 'lactose', 'maltose', 'sucrose',
       'fat', 'saturated_fatty_acids', 'monounsaturated_fatty_acids',
       'polyunsaturated_fatty_acids', 'fatty_acids_total_trans', 'alcohol',
       'ash', 'caffeine', 'theobromine', 'water'],
      dtype='object')

# **76: Changing The Index:**

# * Important Topices******

In [41]:
type(nutrition.index)

pandas.core.indexes.numeric.Int64Index

In [42]:
#nutrition.set_index("name", inplace = False) # inplace must be True is you want change index

In [43]:
#nutrition.set_index("folic_acid", drop = False) # deafualt drop is True which means use colum as index and drop it 
# from columns but if set to false it is going to stay in both as column and index.

In [44]:
nutrition.set_index("name",inplace = True)

In [45]:
nutrition.head(2)

             serving_size  calories total_fat  ... caffeine theobromine   water
name                                           ...
Cornstarch          100 g       381      0.1g  ...  0.00 mg     0.00 mg  8.32 g
Nuts, pecans        100 g       691       72g  ...  0.00 mg     0.00 mg  3.52 g

[2 rows x 75 columns]

# 77: Extracting From DataFrames By Label:

In [46]:
nutrition.sample(1)

                                                   serving_size  ...    water
name                                                             ...
Pork, unheated, separable lean and fat, blade r...        100 g  ...  59.13 g

[1 rows x 75 columns]

In [47]:
nutrition.loc["Eggplant, raw"]

serving_size       100 g
calories              25
total_fat           0.2g
saturated_fat        NaN
cholesterol            0
                  ...
alcohol            0.0 g
ash               0.66 g
caffeine         0.00 mg
theobromine      0.00 mg
water            92.30 g
Name: Eggplant, raw, Length: 75, dtype: object

In [48]:
type(nutrition.loc["Eggplant, raw"])

pandas.core.series.Series

In [49]:
# select espasific items from series or dataframe  
nutrition.loc["Eggplant, raw"]["calories"]

25

In [50]:
#nutrition.loc["Eggplant,axis =0"]["calories"] # Does not work.

In [51]:
nutrition.loc["Eggplant, raw","calories"] # This is another way to get the same result.

25

In [52]:
nutrition.loc["Eggplant, raw":"Sherbet, orange", "calories":"cholesterol"]

                 calories total_fat saturated_fat cholesterol
name
Eggplant, raw          25      0.2g           NaN           0
Teff, uncooked        367      2.4g          0.4g           0
Sherbet, orange       144        2g          1.2g         1mg

# **interpritation: **
normaly our index is integer number but some times it is 

string as well like nutrition dataframe;  to get slice of 

this dataframe we chose from and : to for rows and From :

 to for columns.

In [53]:
# slicing by using list of the indexes and columns we want 
nutrition.loc[
              ["Raspberries, raw","Blackberries, raw"],
              ["protein","vitamin_b6","water"]
]

                  protein vitamin_b6    water
name
Raspberries, raw   1.20 g   0.055 mg  85.75 g
Blackberries, raw  1.39 g   0.030 mg  88.15 g

# NOTE: *** Important*** 

we just choesed 2 rows and 3 columns from nutrition 

dataframe and result is 2 dimantion datafram with 2 rows 

and 3 columns. we can give list of columns and row we want 

to see or work on that.

# 78: DataFrame Extraction By Position:

In [54]:
nutrition.iloc[[4,6,9],:] # this returns 3 rows and all the columns same as .iloc[[4,6,9]]

                   serving_size  calories  ... theobromine    water
name                                       ...
Sherbet, orange           100 g       144  ...     0.00 mg  66.10 g
Taro leaves, raw          100 g        42  ...     0.00 mg  85.66 g
Vegetarian fillets        100 g       290  ...     0.00 mg  45.00 g

[3 rows x 75 columns]

In [55]:
#nutrition.iloc[[4,6,9],"total_fat"]
# This line of code give us error.

In [56]:
nutrition.iloc[[4,6,9],2] # Remember iloc use interger number so here instated of saying "total_fat" column we pass 2

name
Sherbet, orange         2g
Taro leaves, raw      0.7g
Vegetarian fillets     18g
Name: total_fat, dtype: object

In [57]:
nutrition.iloc[[4,6,9], 2:5]

                   total_fat saturated_fat cholesterol
name
Sherbet, orange           2g          1.2g         1mg
Taro leaves, raw        0.7g          0.2g           0
Vegetarian fillets       18g          2.8g           0

## Boolean Masks

NOTE: here we want to chose every other rows and colums 

from our dataset. 

# > IMPORTANT

In [58]:
new_nutrition = nutrition.iloc[
                   [True if i %2 ==0 else False for i in range(8789)],
                   [True if i%2 == 0 else False for i in range(75)]
]

In [59]:
new_nutrition.shape # X/2 rows and y/2 cols

(4395, 38)

In [60]:
nutrition.shape # X rows and y cols

(8789, 75)

In [61]:
new_nutrition.sample(2)

                                                   serving_size  ...    water
name                                                             ...
Chicken, raw, meat and skin and giblets and nec...        100 g  ...  65.98 g
PEPPERIDGE FARM, Whole Grain 100% Whole Wheat B...        100 g  ...  36.90 g

[2 rows x 38 columns]

In [62]:
nutrition.iloc[9,1]

290

In [63]:
#[x for x in range(10) if x %2]. # some things from linked in

## 79: Single value Access with .at and .iat() method.

In [64]:
nutrition.loc["Nuts, pecans",'calories']

691

In [65]:
# OR with iloc
nutrition.iloc[1,1]

691

In [66]:
nutrition.at["Nuts, pecans","calories"] # acts like .loc but only for single value

691

In [67]:
nutrition.iloc[1,1] # same as .iloc but only for single value.  only advantage is these are faster.

691

As you see in codes below at and iat is very faster than loc and iloc.

In [68]:
%timeit nutrition.loc["Nuts, pecans",'calories']

The slowest run took 6.88 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 17 µs per loop

In [69]:
%timeit nutrition.at["Nuts, pecans",'calories']

The slowest run took 7.14 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 10.2 µs per loop

## 80: The get_loc() Method

## 81: Skill challange:

# 82: Solution:

In [70]:
nutr_mini = nutrition.sample(10)

In [71]:
nutr_mini.shape

(10, 75)

In [72]:
#2:
#nutr_mini.iloc[:,[2,4]] # with iloc method 

# with loc method;
nutr_mini.loc[:,["total_fat","cholesterol"]]

                                                   total_fat cholesterol
name
Pork, unheated, separable lean and fat, bone-in...      9.2g        65mg
Pheasant, raw, meat only, leg                           4.3g        80mg
Cereals ready-to-eat, NATURE VALLEY LOW FAT FRU...      4.7g           0
Salad dressing, sweet and sour                            0g           0
Beverages, sweetened, ready-to-drink, green, tea        0.2g           0
Beef, raw, ribs prepared, imported, New Zealand         6.8g        57mg
Soup, ready-to-serve, beef broth or bouillon ca...      0.2g           0
Chrysanthemum leaves, raw                               0.6g           0
KEEBLER, Toast & Peanut Butter Sandwich Crackers         24g           0
Mango, sweetened, dried                                 1.2g           0

In [73]:
#3:
nutr_mini.columns

Index(['serving_size', 'calories', 'total_fat', 'saturated_fat', 'cholesterol',
       'sodium', 'choline', 'folate', 'folic_acid', 'niacin',
       'pantothenic_acid', 'riboflavin', 'thiamin', 'vitamin_a',
       'vitamin_a_rae', 'carotene_alpha', 'carotene_beta',
       'cryptoxanthin_beta', 'lutein_zeaxanthin', 'lucopene', 'vitamin_b12',
       'vitamin_b6', 'vitamin_c', 'vitamin_d', 'vitamin_e', 'tocopherol_alpha',
       'vitamin_k', 'calcium', 'copper', 'irom', 'magnesium', 'manganese',
       'phosphorous', 'potassium', 'selenium', 'zink', 'protein', 'alanine',
       'arginine', 'aspartic_acid', 'cystine', 'glutamic_acid', 'glycine',
       'histidine', 'hydroxyproline', 'isoleucine', 'leucine', 'lysine',
       'methionine', 'phenylalanine', 'proline', 'serine', 'threonine',
       'tryptophan', 'tyrosine', 'valine', 'carbohydrate', 'fiber', 'sugars',
       'fructose', 'galactose', 'glucose', 'lactose', 'maltose', 'sucrose',
       'fat', 'saturated_fatty_acids', 'monounsaturated_fatty_acids',
       'polyunsaturated_fatty_acids', 'fatty_acids_total_trans', 'alcohol',
       'ash', 'caffeine', 'theobromine', 'water'],
      dtype='object')

In [74]:
nutr_mini.iloc[1:4,20:] # This slicing is with iloc method.

                                                   vitamin_b12  ...    water
name                                                            ...
Pheasant, raw, meat only, leg                         0.84 mcg  ...  73.40 g
Cereals ready-to-eat, NATURE VALLEY LOW FAT FRU...    0.00 mcg  ...   5.59 g
Salad dressing, sweet and sour                        0.00 mcg  ...  95.70 g

[3 rows x 55 columns]

In [75]:
# OR
nutrition.columns.get_loc("vitamin_b12")

20

In [76]:
# we can save value in variable and use it like this 
b12_loc = nutrition.columns.get_loc("vitamin_b12")

nutr_mini.iloc[:3, b12_loc:]

                                                   vitamin_b12  ...    water
name                                                            ...
Pork, unheated, separable lean and fat, bone-in...    0.57 mcg  ...  66.09 g
Pheasant, raw, meat only, leg                         0.84 mcg  ...  73.40 g
Cereals ready-to-eat, NATURE VALLEY LOW FAT FRU...    0.00 mcg  ...   5.59 g

[3 rows x 55 columns]

In [77]:
#4:
nutr_mini.iat[2,1]

381

## 83: More Cleanup Going Numeric:

## 84: astype() Method

In [78]:
df= pd.DataFrame({
    "age":[12,13,14,16],
    "weight":[41.1,34.5,83.2,90.1],
    "height":["1.72","1.74","1.91","1.54"]
})

In [79]:
df.head()

   age  weight height
0   12    41.1   1.72
1   13    34.5   1.74
2   14    83.2   1.91
3   16    90.1   1.54

In [80]:
df.info(verbose =0)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     4 non-null      int64
 1   weight  4 non-null      float64
 2   height  4 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 224.0+ bytes

In [81]:
df.astype(float)

    age  weight  height
0  12.0    41.1    1.72
1  13.0    34.5    1.74
2  14.0    83.2    1.91
3  16.0    90.1    1.54

In [82]:
df = df.astype(float)

In [83]:
df.info(verbose = 0)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     4 non-null      float64
 1   weight  4 non-null      float64
 2   height  4 non-null      float64
dtypes: float64(3)
memory usage: 224.0 bytes

In [84]:
df.astype({"age":int})

   age  weight  height
0   12    41.1    1.72
1   13    34.5    1.74
2   14    83.2    1.91
3   16    90.1    1.54

In [85]:
df.astype({"age":np.int16})

   age  weight  height
0   12    41.1    1.72
1   13    34.5    1.74
2   14    83.2    1.91
3   16    90.1    1.54

In [86]:
nutrition.iloc[:4, :]

               serving_size  calories total_fat  ... caffeine theobromine    water
name                                             ...
Cornstarch            100 g       381      0.1g  ...  0.00 mg     0.00 mg   8.32 g
Nuts, pecans          100 g       691       72g  ...  0.00 mg     0.00 mg   3.52 g
Eggplant, raw         100 g        25      0.2g  ...  0.00 mg     0.00 mg  92.30 g
Teff, uncooked        100 g       367      2.4g  ...        0           0   8.82 g

[4 rows x 75 columns]

In [87]:
#nutrition.iloc[:4,:].astype(float)
# This code does not work becuase of .... reasones.

# 85:DataFrame replace() + A Glimpse At Regex

In [88]:
nutrition.iloc[:6,:1]

                 serving_size
name
Cornstarch              100 g
Nuts, pecans            100 g
Eggplant, raw           100 g
Teff, uncooked          100 g
Sherbet, orange         100 g
Cauliflower, raw        100 g

In [89]:
df = nutrition.iloc[:6,:1]

In [90]:
df.replace(to_replace = "100 g",value= 100)

                  serving_size
name
Cornstarch                 100
Nuts, pecans               100
Eggplant, raw              100
Teff, uncooked             100
Sherbet, orange            100
Cauliflower, raw           100

In [91]:
df.replace("g","") # This code does not work.

                 serving_size
name
Cornstarch              100 g
Nuts, pecans            100 g
Eggplant, raw           100 g
Teff, uncooked          100 g
Sherbet, orange         100 g
Cauliflower, raw        100 g

In [92]:
#regex => regular expressions.

In [93]:
df.replace(" g","",regex = True).astype(float) # Option 1:

                  serving_size
name
Cornstarch               100.0
Nuts, pecans             100.0
Eggplant, raw            100.0
Teff, uncooked           100.0
Sherbet, orange          100.0
Cauliflower, raw         100.0

In [94]:
df.replace("\sg","",regex =True).astype(int) #Option 2:

                  serving_size
name
Cornstarch                 100
Nuts, pecans               100
Eggplant, raw              100
Teff, uncooked             100
Sherbet, orange            100
Cauliflower, raw           100

## 86: Part1: Collecting the Units

In [95]:
nutrition.replace("[^a-zA-Z]", "" ,regex = True).head(3)

              serving_size  calories total_fat  ... caffeine theobromine water
name                                            ...
Cornstarch               g       381         g  ...       mg          mg     g
Nuts, pecans             g       691         g  ...       mg          mg     g
Eggplant, raw            g        25         g  ...       mg          mg     g

[3 rows x 75 columns]

In [96]:
nutrition.astype(str).replace('[^a-zA-Z]', "", regex= True).head(3)

              serving_size calories total_fat  ... caffeine theobromine water
name                                           ...
Cornstarch               g                  g  ...       mg          mg     g
Nuts, pecans             g                  g  ...       mg          mg     g
Eggplant, raw            g                  g  ...       mg          mg     g

[3 rows x 75 columns]

In [97]:
units = nutrition.astype(str).replace('[^a-zA-Z]', "", regex= True)

In [98]:
units.head(5)

                serving_size calories total_fat  ... caffeine theobromine water
name                                             ...
Cornstarch                 g                  g  ...       mg          mg     g
Nuts, pecans               g                  g  ...       mg          mg     g
Eggplant, raw              g                  g  ...       mg          mg     g
Teff, uncooked             g                  g  ...                          g
Sherbet, orange            g                  g  ...       mg          mg     g

[5 rows x 75 columns]

In [99]:
units.mode()

  serving_size calories total_fat saturated_fat  ... ash caffeine theobromine water
0            g                  g             g  ...   g       mg          mg     g

[1 rows x 75 columns]

In [100]:
units.saturated_fat.value_counts()

g      7199
nan    1590
Name: saturated_fat, dtype: int64

In [101]:
units.saturated_fat.mode()

0    g
dtype: object

In [102]:
units= units.mode()

In [103]:
units

  serving_size calories total_fat saturated_fat  ... ash caffeine theobromine water
0            g                  g             g  ...   g       mg          mg     g

[1 rows x 75 columns]

# 87: The Rename() Method:

In [104]:
df= pd.DataFrame({
    "age":[12,13,14,16],
    "weight":[41.1,34.5,83.2,90.1],
    "height":["1.72","1.74","1.91","1.54"]
})

In [105]:
df.head()

   age  weight height
0   12    41.1   1.72
1   13    34.5   1.74
2   14    83.2   1.91
3   16    90.1   1.54

In [106]:
df.rename({"age":"Ages"}, axis = 1) # use axis = 1 or columns name for changing name of the coulumns.

   Ages  weight height
0    12    41.1   1.72
1    13    34.5   1.74
2    14    83.2   1.91
3    16    90.1   1.54

In [107]:
df.rename(columns ={"age":"Ages","weight":"Weights"}) # use axis = 1 or columns name for changing name of the coulumns.

   Ages  Weights height
0    12     41.1   1.72
1    13     34.5   1.74
2    14     83.2   1.91
3    16     90.1   1.54

In [108]:
df.rename({0:"Elyar"}) # defualt axis is 0 or rows.

       age  weight height
Elyar   12    41.1   1.72
1       13    34.5   1.74
2       14    83.2   1.91
3       16    90.1   1.54

In [109]:
df.rename({0:"Elyar",1:"Sal",2:"Arran"},axis =0)

       age  weight height
Elyar   12    41.1   1.72
Sal     13    34.5   1.74
Arran   14    83.2   1.91
3       16    90.1   1.54

In [110]:
df.rename(mapper={"age":"AGES","height":"Hights"}) # NOTE: becuase defualt axis is axis = 0 nothings happens here but we do not get erros as well.

   age  weight height
0   12    41.1   1.72
1   13    34.5   1.74
2   14    83.2   1.91
3   16    90.1   1.54

In [111]:
df.rename(mapper=({"age":"AGES","height":"Height"}),axis =1) # axis = 1 and we need to use inplace = True as well.

   AGES  weight Height
0    12    41.1   1.72
1    13    34.5   1.74
2    14    83.2   1.91
3    16    90.1   1.54

In [112]:
df

   age  weight height
0   12    41.1   1.72
1   13    34.5   1.74
2   14    83.2   1.91
3   16    90.1   1.54

In [113]:
df.rename(mapper=({"age":"Age","height":"Height","weight":"Weight"}),axis =1, inplace = True) # axis = 1 and we need to use inplace = True as well.

In [114]:
df.head(2)

   Age  Weight Height
0   12    41.1   1.72
1   13    34.5   1.74

# 88:DataFrame dropna()

In [115]:
df

   Age  Weight Height
0   12    41.1   1.72
1   13    34.5   1.74
2   14    83.2   1.91
3   16    90.1   1.54

In [116]:
df.loc[2,"Weight"] = np.nan

In [117]:
df

   Age  Weight Height
0   12    41.1   1.72
1   13    34.5   1.74
2   14     NaN   1.91
3   16    90.1   1.54

In [118]:
df.loc[1,:] =np.nan

In [119]:
df

    Age  Weight Height
0  12.0    41.1   1.72
1   NaN     NaN    NaN
2  14.0     NaN   1.91
3  16.0    90.1   1.54

In [120]:
df.dropna() # This line of code drop any rows from dataframe which they have min 1 NaN

    Age  Weight Height
0  12.0    41.1   1.72
3  16.0    90.1   1.54

In [121]:
df.dropna(how = "any", axis = 0) # same as perivuos line

    Age  Weight Height
0  12.0    41.1   1.72
3  16.0    90.1   1.54

In [122]:
df.dropna(how = "all",axis = 0) # all row must be nan

    Age  Weight Height
0  12.0    41.1   1.72
2  14.0     NaN   1.91
3  16.0    90.1   1.54

In [123]:
# Thresh
df.dropna(thresh = 3,axis =0)

    Age  Weight Height
0  12.0    41.1   1.72
3  16.0    90.1   1.54

In [124]:
df.dropna(thresh=3)

    Age  Weight Height
0  12.0    41.1   1.72
3  16.0    90.1   1.54

In [125]:
df.dropna(axis =1) # becuae all the columns has NaN values.

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [126]:
df.dropna(axis = 1, how = "all") # this line drops any columns if all of the values in columns are nan which is not correct in our case.

    Age  Weight Height
0  12.0    41.1   1.72
1   NaN     NaN    NaN
2  14.0     NaN   1.91
3  16.0    90.1   1.54

In [127]:
df.dropna(thresh=2,axis =1) # OR df.dropna(axis =1, thresh = 2)

    Age  Weight Height
0  12.0    41.1   1.72
1   NaN     NaN    NaN
2  14.0     NaN   1.91
3  16.0    90.1   1.54

# 89: BONUS- dropna() With Subset

In [128]:
# check it from orginal vedio

# 90: Part 2: Merging Units With Column Names:

In [129]:
units

  serving_size calories total_fat saturated_fat  ... ash caffeine theobromine water
0            g                  g             g  ...   g       mg          mg     g

[1 rows x 75 columns]

In [130]:
# The rename Method

In [131]:
#### DETOUR: dataFrame ineration

In [132]:
for k in units:
  print(k)

serving_size
calories
total_fat
saturated_fat
cholesterol
sodium
choline
folate
folic_acid
niacin
pantothenic_acid
riboflavin
thiamin
vitamin_a
vitamin_a_rae
carotene_alpha
carotene_beta
cryptoxanthin_beta
lutein_zeaxanthin
lucopene
vitamin_b12
vitamin_b6
vitamin_c
vitamin_d
vitamin_e
tocopherol_alpha
vitamin_k
calcium
copper
irom
magnesium
manganese
phosphorous
potassium
selenium
zink
protein
alanine
arginine
aspartic_acid
cystine
glutamic_acid
glycine
histidine
hydroxyproline
isoleucine
leucine
lysine
methionine
phenylalanine
proline
serine
threonine
tryptophan
tyrosine
valine
carbohydrate
fiber
sugars
fructose
galactose
glucose
lactose
maltose
sucrose
fat
saturated_fatty_acids
monounsaturated_fatty_acids
polyunsaturated_fatty_acids
fatty_acids_total_trans
alcohol
ash
caffeine
theobromine
water

In [133]:
for k in units:
  print(k, units[k]) # This is not what we want to see.

serving_size 0    g
Name: serving_size, dtype: object
calories 0
Name: calories, dtype: object
total_fat 0    g
Name: total_fat, dtype: object
saturated_fat 0    g
Name: saturated_fat, dtype: object
cholesterol 0    mg
Name: cholesterol, dtype: object
sodium 0    mg
Name: sodium, dtype: object
choline 0    mg
Name: choline, dtype: object
folate 0    mcg
Name: folate, dtype: object
folic_acid 0    mcg
Name: folic_acid, dtype: object
niacin 0    mg
Name: niacin, dtype: object
pantothenic_acid 0    mg
Name: pantothenic_acid, dtype: object
riboflavin 0    mg
Name: riboflavin, dtype: object
thiamin 0    mg
Name: thiamin, dtype: object
vitamin_a 0    IU
Name: vitamin_a, dtype: object
vitamin_a_rae 0    mcg
Name: vitamin_a_rae, dtype: object
carotene_alpha 0    mcg
Name: carotene_alpha, dtype: object
carotene_beta 0    mcg
Name: carotene_beta, dtype: object
cryptoxanthin_beta 0    mcg
Name: cryptoxanthin_beta, dtype: object
lutein_zeaxanthin 0    mcg
Name: lutein_zeaxanthin, dtype: object
lucopene 0
Name: lucopene, dtype: object
vitamin_b12 0    mcg
Name: vitamin_b12, dtype: object
vitamin_b6 0    mg
Name: vitamin_b6, dtype: object
vitamin_c 0    mg
Name: vitamin_c, dtype: object
vitamin_d 0    IU
Name: vitamin_d, dtype: object
vitamin_e 0    mg
Name: vitamin_e, dtype: object
tocopherol_alpha 0    mg
Name: tocopherol_alpha, dtype: object
vitamin_k 0    mcg
Name: vitamin_k, dtype: object
calcium 0    mg
Name: calcium, dtype: object
copper 0    mg
Name: copper, dtype: object
irom 0    mg
Name: irom, dtype: object
magnesium 0    mg
Name: magnesium, dtype: object
manganese 0    mg
Name: manganese, dtype: object
phosphorous 0    mg
Name: phosphorous, dtype: object
potassium 0    mg
Name: potassium, dtype: object
selenium 0    mcg
Name: selenium, dtype: object
zink 0    mg
Name: zink, dtype: object
protein 0    g
Name: protein, dtype: object
alanine 0    g
Name: alanine, dtype: object
arginine 0    g
Name: arginine, dtype: object
aspartic_acid 0    g
Name: aspartic_acid, dtype: object
cystine 0    g
Name: cystine, dtype: object
glutamic_acid 0    g
Name: glutamic_acid, dtype: object
glycine 0    g
Name: glycine, dtype: object
histidine 0    g
Name: histidine, dtype: object
hydroxyproline 0
Name: hydroxyproline, dtype: object
isoleucine 0    g
Name: isoleucine, dtype: object
leucine 0    g
Name: leucine, dtype: object
lysine 0    g
Name: lysine, dtype: object
methionine 0    g
Name: methionine, dtype: object
phenylalanine 0    g
Name: phenylalanine, dtype: object
proline 0    g
Name: proline, dtype: object
serine 0    g
Name: serine, dtype: object
threonine 0    g
Name: threonine, dtype: object
tryptophan 0    g
Name: tryptophan, dtype: object
tyrosine 0    g
Name: tyrosine, dtype: object
valine 0    g
Name: valine, dtype: object
carbohydrate 0    g
Name: carbohydrate, dtype: object
fiber 0    g
Name: fiber, dtype: object
sugars 0    g
Name: sugars, dtype: object
fructose 0
Name: fructose, dtype: object
galactose 0
Name: galactose, dtype: object
glucose 0
Name: glucose, dtype: object
lactose 0
Name: lactose, dtype: object
maltose 0
Name: maltose, dtype: object
sucrose 0
Name: sucrose, dtype: object
fat 0    g
Name: fat, dtype: object
saturated_fatty_acids 0    g
Name: saturated_fatty_acids, dtype: object
monounsaturated_fatty_acids 0    g
Name: monounsaturated_fatty_acids, dtype: object
polyunsaturated_fatty_acids 0    g
Name: polyunsaturated_fatty_acids, dtype: object
fatty_acids_total_trans 0    mg
Name: fatty_acids_total_trans, dtype: object
alcohol 0    g
Name: alcohol, dtype: object
ash 0    g
Name: ash, dtype: object
caffeine 0    mg
Name: caffeine, dtype: object
theobromine 0    mg
Name: theobromine, dtype: object
water 0    g
Name: water, dtype: object

In [134]:
for k in units:
  print(k,units[k].at[0]) # This gives us columns name and first value in that column.

serving_size g
calories
total_fat g
saturated_fat g
cholesterol mg
sodium mg
choline mg
folate mcg
folic_acid mcg
niacin mg
pantothenic_acid mg
riboflavin mg
thiamin mg
vitamin_a IU
vitamin_a_rae mcg
carotene_alpha mcg
carotene_beta mcg
cryptoxanthin_beta mcg
lutein_zeaxanthin mcg
lucopene
vitamin_b12 mcg
vitamin_b6 mg
vitamin_c mg
vitamin_d IU
vitamin_e mg
tocopherol_alpha mg
vitamin_k mcg
calcium mg
copper mg
irom mg
magnesium mg
manganese mg
phosphorous mg
potassium mg
selenium mcg
zink mg
protein g
alanine g
arginine g
aspartic_acid g
cystine g
glutamic_acid g
glycine g
histidine g
hydroxyproline
isoleucine g
leucine g
lysine g
methionine g
phenylalanine g
proline g
serine g
threonine g
tryptophan g
tyrosine g
valine g
carbohydrate g
fiber g
sugars g
fructose
galactose
glucose
lactose
maltose
sucrose
fat g
saturated_fatty_acids g
monounsaturated_fatty_acids g
polyunsaturated_fatty_acids g
fatty_acids_total_trans mg
alcohol g
ash g
caffeine mg
theobromine mg
water g

In [135]:
for k in units:
  print(units[k].at[0]) # This code return us only units not columns name

g

g
g
mg
mg
mg
mcg
mcg
mg
mg
mg
mg
IU
mcg
mcg
mcg
mcg
mcg

mcg
mg
mg
IU
mg
mg
mcg
mg
mg
mg
mg
mg
mg
mg
mcg
mg
g
g
g
g
g
g
g
g

g
g
g
g
g
g
g
g
g
g
g
g
g
g






g
g
g
g
mg
g
g
mg
mg
g

In [136]:
units = units.replace("", np.nan).dropna(axis = 1)

In [137]:
units.shape

(1, 66)

In [138]:
for k in units:
  print(k,units[k].at[0]) # there you go there is no gap any more in units dataframe.

serving_size g
total_fat g
saturated_fat g
cholesterol mg
sodium mg
choline mg
folate mcg
folic_acid mcg
niacin mg
pantothenic_acid mg
riboflavin mg
thiamin mg
vitamin_a IU
vitamin_a_rae mcg
carotene_alpha mcg
carotene_beta mcg
cryptoxanthin_beta mcg
lutein_zeaxanthin mcg
vitamin_b12 mcg
vitamin_b6 mg
vitamin_c mg
vitamin_d IU
vitamin_e mg
tocopherol_alpha mg
vitamin_k mcg
calcium mg
copper mg
irom mg
magnesium mg
manganese mg
phosphorous mg
potassium mg
selenium mcg
zink mg
protein g
alanine g
arginine g
aspartic_acid g
cystine g
glutamic_acid g
glycine g
histidine g
isoleucine g
leucine g
lysine g
methionine g
phenylalanine g
proline g
serine g
threonine g
tryptophan g
tyrosine g
valine g
carbohydrate g
fiber g
sugars g
fat g
saturated_fatty_acids g
monounsaturated_fatty_acids g
polyunsaturated_fatty_acids g
fatty_acids_total_trans mg
alcohol g
ash g
caffeine mg
theobromine mg
water g

In [139]:
#{
 #  "serving_size":"serving_size_g",
 # "total_fat": "total_fat_g" 
 #......

#}

# what we are trying to do is change the name of the columns to columns name + units so it is beter to do in for loop and mapper function.

In [140]:
mapper= {k:k+"_"+units[k].at[0]for k in units}

In [141]:
mapper

{'alanine': 'alanine_g',
 'alcohol': 'alcohol_g',
 'arginine': 'arginine_g',
 'ash': 'ash_g',
 'aspartic_acid': 'aspartic_acid_g',
 'caffeine': 'caffeine_mg',
 'calcium': 'calcium_mg',
 'carbohydrate': 'carbohydrate_g',
 'carotene_alpha': 'carotene_alpha_mcg',
 'carotene_beta': 'carotene_beta_mcg',
 'cholesterol': 'cholesterol_mg',
 'choline': 'choline_mg',
 'copper': 'copper_mg',
 'cryptoxanthin_beta': 'cryptoxanthin_beta_mcg',
 'cystine': 'cystine_g',
 'fat': 'fat_g',
 'fatty_acids_total_trans': 'fatty_acids_total_trans_mg',
 'fiber': 'fiber_g',
 'folate': 'folate_mcg',
 'folic_acid': 'folic_acid_mcg',
 'glutamic_acid': 'glutamic_acid_g',
 'glycine': 'glycine_g',
 'histidine': 'histidine_g',
 'irom': 'irom_mg',
 'isoleucine': 'isoleucine_g',
 'leucine': 'leucine_g',
 'lutein_zeaxanthin': 'lutein_zeaxanthin_mcg',
 'lysine': 'lysine_g',
 'magnesium': 'magnesium_mg',
 'manganese': 'manganese_mg',
 'methionine': 'methionine_g',
 'monounsaturated_fatty_acids': 'monounsaturated_fatty_acids_g',
 'niacin': 'niacin_mg',
 'pantothenic_acid': 'pantothenic_acid_mg',
 'phenylalanine': 'phenylalanine_g',
 'phosphorous': 'phosphorous_mg',
 'polyunsaturated_fatty_acids': 'polyunsaturated_fatty_acids_g',
 'potassium': 'potassium_mg',
 'proline': 'proline_g',
 'protein': 'protein_g',
 'riboflavin': 'riboflavin_mg',
 'saturated_fat': 'saturated_fat_g',
 'saturated_fatty_acids': 'saturated_fatty_acids_g',
 'selenium': 'selenium_mcg',
 'serine': 'serine_g',
 'serving_size': 'serving_size_g',
 'sodium': 'sodium_mg',
 'sugars': 'sugars_g',
 'theobromine': 'theobromine_mg',
 'thiamin': 'thiamin_mg',
 'threonine': 'threonine_g',
 'tocopherol_alpha': 'tocopherol_alpha_mg',
 'total_fat': 'total_fat_g',
 'tryptophan': 'tryptophan_g',
 'tyrosine': 'tyrosine_g',
 'valine': 'valine_g',
 'vitamin_a': 'vitamin_a_IU',
 'vitamin_a_rae': 'vitamin_a_rae_mcg',
 'vitamin_b12': 'vitamin_b12_mcg',
 'vitamin_b6': 'vitamin_b6_mg',
 'vitamin_c': 'vitamin_c_mg',
 'vitamin_d': 'vitamin_d_IU',
 'vitamin_e': 'vitamin_e_mg',
 'vitamin_k': 'vitamin_k_mcg',
 'water': 'water_g',
 'zink': 'zink_mg'}

In [142]:
nutrition.rename(columns = mapper,inplace = True) # this code only effect columns they have unites e.g calories columns does not have units.

In [143]:
nutrition.head(1)

           serving_size_g  calories  ... theobromine_mg water_g
name                                 ...
Cornstarch          100 g       381  ...        0.00 mg  8.32 g

[1 rows x 75 columns]

# 91: Part3: Removing units from values.

In [144]:
nutrition.replace("[a-zA-Z]","",regex = True, inplace = True) # Remove all the characters

In [145]:
nutrition.head()

                serving_size_g  calories  ... theobromine_mg water_g
name                                      ...
Cornstarch                100        381  ...          0.00    8.32
Nuts, pecans              100        691  ...          0.00    3.52
Eggplant, raw             100         25  ...          0.00   92.30
Teff, uncooked            100        367  ...              0   8.82
Sherbet, orange           100        144  ...          0.00   66.10

[5 rows x 75 columns]

In [146]:
nutrition.dtypes

serving_size_g     object
calories            int64
total_fat_g        object
saturated_fat_g    object
cholesterol_mg     object
                    ...
alcohol_g          object
ash_g              object
caffeine_mg        object
theobromine_mg     object
water_g            object
Length: 75, dtype: object

In [147]:
nutrition.dtypes.value_counts()

object    73
int64      2
dtype: int64

In [148]:
nutrition= nutrition.astype(float)

In [149]:
nutrition.dtypes.value_counts()

float64    75
dtype: int64

In [150]:
nutrition.head()

                 serving_size_g  calories  ...  theobromine_mg  water_g
name                                       ...
Cornstarch                100.0     381.0  ...             0.0     8.32
Nuts, pecans              100.0     691.0  ...             0.0     3.52
Eggplant, raw             100.0      25.0  ...             0.0    92.30
Teff, uncooked            100.0     367.0  ...             0.0     8.82
Sherbet, orange           100.0     144.0  ...             0.0    66.10

[5 rows x 75 columns]

# 92:Filtering IN 2D

In [151]:
nutrition.shape

(8789, 75)

In [152]:
nutrition.filter(like = "octopus",axis =0) # like parameter is case sensitive. with capital Octopus we get diffrent result.

                                               serving_size_g  ...  water_g
name                                                           ...
Mollusks, raw, common, octopus                          100.0  ...    80.25
Mollusks, moist heat, cooked, common, octopus           100.0  ...    60.50

[2 rows x 75 columns]

In [153]:
# Filter with regex:
nutrition.filter(regex= "octopus", axis = 0) # regex parameter is casesensitive as well

                                               serving_size_g  ...  water_g
name                                                           ...
Mollusks, raw, common, octopus                          100.0  ...    80.25
Mollusks, moist heat, cooked, common, octopus           100.0  ...    60.50

[2 rows x 75 columns]

In [154]:
# This returns any row with octupus either it start with upper case or lower case o.
nutrition.filter(regex= "[Oo]ctopus",axis =0)

                                               serving_size_g  ...  water_g
name                                                           ...
Octopus (Alaska Native)                                 100.0  ...    84.00
Mollusks, raw, common, octopus                          100.0  ...    80.25
Mollusks, moist heat, cooked, common, octopus           100.0  ...    60.50

[3 rows x 75 columns]

In [155]:
# 2ND option: in regex (?i) means not case sensitive 
nutrition.filter(regex ="(?i)octopus",axis = 0)

                                               serving_size_g  ...  water_g
name                                                           ...
Octopus (Alaska Native)                                 100.0  ...    84.00
Mollusks, raw, common, octopus                          100.0  ...    80.25
Mollusks, moist heat, cooked, common, octopus           100.0  ...    60.50

[3 rows x 75 columns]

# Filttering along both Dime

In [156]:
# First option:
nutrition.filter(regex = "(?i)octopus",axis = 0)\
    .filter(items = ["cholesterol_mg","serving_size_g","calories"],axis = 1)

                                               cholesterol_mg  ...  calories
name                                                           ...
Octopus (Alaska Native)                                  41.0  ...      56.0
Mollusks, raw, common, octopus                           48.0  ...      82.0
Mollusks, moist heat, cooked, common, octopus            96.0  ...     164.0

[3 rows x 3 columns]

In [157]:
#2ND: option:
nutrition.filter(regex= "(?i)octopus",axis = 0)\
          .loc[:, ["cholesterol_mg","serving_size_g","calories"]]

                                               cholesterol_mg  ...  calories
name                                                           ...
Octopus (Alaska Native)                                  41.0  ...      56.0
Mollusks, raw, common, octopus                           48.0  ...      82.0
Mollusks, moist heat, cooked, common, octopus            96.0  ...     164.0

[3 rows x 3 columns]

# 93: DataFrame Sorting:

In [158]:
nutrition.sort_values(by = ["calories"],ascending= False).head(3)

                    serving_size_g  calories  ...  theobromine_mg  water_g
name                                          ...
Fat, mutton tallow           100.0     902.0  ...             0.0      0.0
Fish oil, salmon             100.0     902.0  ...             0.0      0.0
Lard                         100.0     902.0  ...             0.0      0.0

[3 rows x 75 columns]

In [159]:
nutrition.sort_values(by =["cholesterol_mg","sodium_mg"],ascending = False).head(3)

                                                    serving_size_g  ...  water_g
name                                                                ...
Veal, braised, cooked, brain, variety meats and...           100.0  ...    76.89
Beef, simmered, cooked, brain, variety meats an...           100.0  ...    74.86
Beef, raw, brain, variety meats and by-products              100.0  ...    76.29

[3 rows x 75 columns]

In [160]:
nutrition.sort_values(by= ["cholesterol_mg","sodium_mg"], ascending =[False, True]).head(3)

                                                    serving_size_g  ...  water_g
name                                                                ...
Beef, simmered, cooked, brain, variety meats an...           100.0  ...    74.86
Veal, braised, cooked, brain, variety meats and...           100.0  ...    76.89
Beef, raw, brain, variety meats and by-products              100.0  ...    76.29

[3 rows x 75 columns]

In [161]:
# Brain composition detour:

In [162]:
nutrition.loc["Beef, simmered, cooked, brain, variety meats and by-products"].filter(like ="_g").sort_values(ascending = False )

serving_size_g                   100.000
water_g                           74.860
protein_g                         11.670
total_fat_g                       11.000
fat_g                             10.530
saturated_fat_g                    2.400
saturated_fatty_acids_g            2.394
monounsaturated_fatty_acids_g      1.882
polyunsaturated_fatty_acids_g      1.632
carbohydrate_g                     1.480
ash_g                              1.460
threonine_g                        0.000
alcohol_g                          0.000
sugars_g                           0.000
fiber_g                            0.000
valine_g                           0.000
tyrosine_g                         0.000
tryptophan_g                       0.000
serine_g                           0.000
phenylalanine_g                    0.000
methionine_g                       0.000
lysine_g                           0.000
leucine_g                          0.000
isoleucine_g                       0.000
histidine_g                        0.000
glycine_g                          0.000
glutamic_acid_g                    0.000
cystine_g                          0.000
aspartic_acid_g                    0.000
arginine_g                         0.000
alanine_g                          0.000
proline_g                          0.000
Name: Beef, simmered, cooked, brain, variety meats and by-products, dtype: float64

# 94: Using Series between() With DataFrames

In [163]:
#nutrition.between()

In [164]:
nutrition.calories.head()

name
Cornstarch         381.0
Nuts, pecans       691.0
Eggplant, raw       25.0
Teff, uncooked     367.0
Sherbet, orange    144.0
Name: calories, dtype: float64

In [165]:
#nutrition.calories.value_counts()

In [166]:
nutrition.shape

(8789, 75)

In [167]:
nutrition["calories"].shape

(8789,)

In [168]:
nutrition["calories"].between(20,60)

name
Cornstarch                                                                                            False
Nuts, pecans                                                                                          False
Eggplant, raw                                                                                          True
Teff, uncooked                                                                                        False
Sherbet, orange                                                                                       False
                                                                                                      ...
Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round roast, round    False
Lamb, cooked, separable lean only, composite of trimmed retail cuts, frozen, imported, New Zealand    False
Lamb, raw, separable lean and fat, composite of trimmed retail cuts, frozen, imported, New Zealand    False
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round roast, round    False
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round    False
Name: calories, Length: 8789, dtype: bool

In [169]:
nutrition["calories"].between(20,60).shape

(8789,)

In [170]:
nutrition[nutrition["calories"].between(20,60)].head()

                      serving_size_g  calories  ...  theobromine_mg  water_g
name                                            ...
Eggplant, raw                  100.0      25.0  ...             0.0    92.30
Cauliflower, raw               100.0      25.0  ...             0.0    92.07
Taro leaves, raw               100.0      42.0  ...             0.0    85.66
PACE, Picante Sauce            100.0      25.0  ...             0.0    89.90
Mango nectar, canned           100.0      51.0  ...             0.0    86.63

[5 rows x 75 columns]

In [171]:
nutrition[nutrition.calories.between(20,60)].shape

(1190, 75)

# 95: Min,Max And idx[MinMax]

In [172]:
nutrition.min()

serving_size_g     100.0
calories             0.0
total_fat_g          0.0
saturated_fat_g      0.1
cholesterol_mg       0.0
                   ...
alcohol_g            0.0
ash_g                0.0
caffeine_mg          0.0
theobromine_mg       0.0
water_g              0.0
Length: 75, dtype: float64

In [173]:
nutrition.min(axis =1)

name
Cornstarch                                                                                            0.0
Nuts, pecans                                                                                          0.0
Eggplant, raw                                                                                         0.0
Teff, uncooked                                                                                        0.0
Sherbet, orange                                                                                       0.0
                                                                                                     ...
Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round roast, round    0.0
Lamb, cooked, separable lean only, composite of trimmed retail cuts, frozen, imported, New Zealand    0.0
Lamb, raw, separable lean and fat, composite of trimmed retail cuts, frozen, imported, New Zealand    0.0
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round roast, round    0.0
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round    0.0
Length: 8789, dtype: float64

In [174]:
nutrition.max(axis =1)

name
Cornstarch                                                                                            381.0
Nuts, pecans                                                                                          691.0
Eggplant, raw                                                                                         229.0
Teff, uncooked                                                                                        429.0
Sherbet, orange                                                                                       144.0
                                                                                                      ...
Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round roast, round    311.0
Lamb, cooked, separable lean only, composite of trimmed retail cuts, frozen, imported, New Zealand    246.0
Lamb, raw, separable lean and fat, composite of trimmed retail cuts, frozen, imported, New Zealand    277.0
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round roast, round    319.0
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round    319.0
Length: 8789, dtype: float64

In [175]:
#What food has the most potassium

In [176]:
#nutrition.potassium_mg.max() 
nutrition["potassium_mg"].max()

16500.0

In [177]:
nutrition.potassium_mg.idxmax() # this code show the location of the food which has max potassium = 16500.0

'Leavening agents, cream of tartar'

In [178]:
nutrition["potassium_mg"].sort_values(ascending = False).head(6)

name
Leavening agents, cream of tartar                      16500.0
Leavening agents, low-sodium, baking powder            10100.0
Parsley, freeze-dried                                   6300.0
Beverages, unsweetened, decaffeinated, instant, tea     6040.0
Beverages, powder, unsweetened, instant, tea            6040.0
Spices, dried, chervil                                  4740.0
Name: potassium_mg, dtype: float64

In [179]:
# Targeting: potassium to sodium == 16

In [180]:
K_to_NA = (nutrition["potassium_mg"].replace(0,1)/ nutrition["sodium_mg"].replace(0,1))\
  .sort_values(ascending = False)

In [181]:
K_to_NA.head()

name
Peanut flour, low fat                                         1358.0
Nuts, raw, pistachio nuts                                     1025.0
Beverages, reduced calorie, with whitener, instant, coffee     909.0
Soybeans, raw, mature seeds                                    898.5
Soy meal, raw, defatted                                        830.0
dtype: float64

In [182]:
K_to_NA[K_to_NA.between(14,18)].sample(7)

name
Babyfood, peas and brown rice                                15.500000
Alcoholic beverage, white, table, wine                       14.200000
Couscous, dry                                                16.600000
Onions, unprepared, whole, frozen                            14.200000
Fruit cocktail, drained, heavy syrup, canned                 15.000000
Onions, raw, spring or scallions (includes tops and bulb)    17.250000
Tomato products, without salt added, paste, canned           17.186441
dtype: float64

In [183]:
K_to_NA.shape

(8789,)

# 96: DataFrame nlargest() And nsmallest()

In [184]:
# 2ND way to do get the same result:
nutrition.nlargest(10,columns ="potassium_mg").potassium_mg

name
Leavening agents, cream of tartar                         16500.0
Leavening agents, low-sodium, baking powder               10100.0
Parsley, freeze-dried                                      6300.0
Beverages, powder, unsweetened, instant, tea               6040.0
Beverages, unsweetened, decaffeinated, instant, tea        6040.0
Spices, dried, chervil                                     4740.0
Spices, dried, coriander leaf                              4466.0
Celery flakes, dried                                       4388.0
Beverages, powder, regular, instant, coffee                3535.0
Beverages, half the caffeine, regular, instant, coffee     3535.0
Name: potassium_mg, dtype: float64

In [185]:
# 3RD option:
nutrition.nlargest(10,columns ="potassium_mg")["potassium_mg"]

name
Leavening agents, cream of tartar                         16500.0
Leavening agents, low-sodium, baking powder               10100.0
Parsley, freeze-dried                                      6300.0
Beverages, powder, unsweetened, instant, tea               6040.0
Beverages, unsweetened, decaffeinated, instant, tea        6040.0
Spices, dried, chervil                                     4740.0
Spices, dried, coriander leaf                              4466.0
Celery flakes, dried                                       4388.0
Beverages, powder, regular, instant, coffee                3535.0
Beverages, half the caffeine, regular, instant, coffee     3535.0
Name: potassium_mg, dtype: float64

In [186]:
#nutrition.nlargest(10,columns =["potassium_mg","sodium_mg"]).potassium_mg

In [187]:
# Best way is this way:
nutrition["potassium_mg"].nlargest(10)

name
Leavening agents, cream of tartar                         16500.0
Leavening agents, low-sodium, baking powder               10100.0
Parsley, freeze-dried                                      6300.0
Beverages, powder, unsweetened, instant, tea               6040.0
Beverages, unsweetened, decaffeinated, instant, tea        6040.0
Spices, dried, chervil                                     4740.0
Spices, dried, coriander leaf                              4466.0
Celery flakes, dried                                       4388.0
Beverages, powder, regular, instant, coffee                3535.0
Beverages, half the caffeine, regular, instant, coffee     3535.0
Name: potassium_mg, dtype: float64

In [188]:
#nutrition.nsmallest(10#)

In [189]:
nutrition["potassium_mg"].nsmallest(10)

name
PACE, Picante Sauce       0.0
Goji berries, dried       0.0
PACE, Green Taco Sauce    0.0
Chewing gum, sugarless    0.0
Oil, soybean lecithin     0.0
SILK Original Creamer     0.0
SILK Hazelnut Creamer     0.0
SILK Peach soy yogurt     0.0
SILK Plain soy yogurt     0.0
PACE, Enchilada Sauce     0.0
Name: potassium_mg, dtype: float64

# 97: Skilles challeng:

In [190]:
# 1: fin the 10 foods that have most Vitamin B12 what do they have in common?

In [191]:
# First option:
nutrition.loc[:,"vitamin_b12_mcg"].nlargest(3)

name
Mollusks, moist heat, cooked, mixed species, clam                                   98.89
Beef, boiled, cooked, variety meats and by-products liver, imported, New Zealand    96.00
Lamb, raw, liver, variety meats and by-products                                     90.05
Name: vitamin_b12_mcg, dtype: float64

In [192]:
# 2option: 
nutrition["vitamin_b12_mcg"].nlargest(3)

name
Mollusks, moist heat, cooked, mixed species, clam                                   98.89
Beef, boiled, cooked, variety meats and by-products liver, imported, New Zealand    96.00
Lamb, raw, liver, variety meats and by-products                                     90.05
Name: vitamin_b12_mcg, dtype: float64

In [193]:
# 3Rd option:
nutrition.nlargest(3,columns = "vitamin_b12_mcg").vitamin_b12_mcg

name
Mollusks, moist heat, cooked, mixed species, clam                                   98.89
Beef, boiled, cooked, variety meats and by-products liver, imported, New Zealand    96.00
Lamb, raw, liver, variety meats and by-products                                     90.05
Name: vitamin_b12_mcg, dtype: float64

In [194]:
# Isolate the foods in the dataset that contain,or are based on ,eggplant.which of them has the most sodium?
#nutrition.filter(like = "eggplant", axis = 0)
nutrition.filter(regex ="(?i)eggplant",axis = 0).shape

(4, 75)

In [195]:
nutrition.filter(regex ="(?i)eggplant",axis =0).sodium_mg.nlargest(1)

name
Eggplant, pickled    1674.0
Name: sodium_mg, dtype: float64

In [196]:
# Select Slice of the dataFrame that contains 4 random rows and 2 random columns. 
#nutrition.sample(4,axis =1)
nutrition.sample(4,axis=0).sample(2,axis =1) # Defualt axis is rows or 0

                                                    zink_mg  aspartic_acid_g
name
KASHI, Original, H2H Woven Wheat Cracker               3.30            0.000
Pork, cooked, separable lean only, composite of...     2.90            2.624
Crustaceans, raw, queen, crab                          2.80            1.912
Rice, raw, medium-grain, brown                         2.02            0.702

# **99. Skill challange 2**
very important challange.